version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: concord_postgres
    environment:
      POSTGRES_USER: concord
      POSTGRES_PASSWORD: concord
      POSTGRES_DB: concord
    ports:
      - '5432:5432'
    expose:
      - 5432
