version: '3.8'

services:
  postgres1:
    image: postgres:latest
    container_name: concord_builder
    environment:
      POSTGRES_USER: builder
      POSTGRES_PASSWORD: builder
      POSTGRES_DB: builder
    ports:
      - '5433:5432' # Expose this PostgreSQL instance at port 5433 on the host
    expose:
      - 5432 # Internal port 5432 remains unchanged

  postgres2:
    image: postgres:latest
    container_name: concord_playground
    environment:
      POSTGRES_USER: playground
      POSTGRES_PASSWORD: playground
      POSTGRES_DB: playground
    ports:
      - '5434:5432' # Expose this PostgreSQL instance at port 5434 on the host
    expose:
      - 5432 # Internal port 5432 remains unchanged
